In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/results.csv', encoding='utf-8')
df1 = pd.read_csv(r'https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/schema.csv', encoding='utf-8')

C:\Users\matvi\AppData\Local\Temp\ipykernel_16052\1763740257.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'https://media.githubusercontent.com/media/StackExchange/Survey/refs/heads/main/packages/archive/2025/results.csv', encoding='utf-8')

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [5]:
df1.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   qid       139 non-null    object
 1   qname     139 non-null    object
 2   question  139 non-null    object
 3   type      139 non-null    object
 4   sub       49 non-null     object
 5   sq_id     49 non-null     float64
dtypes: float64(1), object(5)
memory usage: 6.6+ KB

Завдання 1. Підрахунок загальної кількості респондентів

In [8]:
df['ResponseId'].nunique()

49191

Завдання 2. Аналіз повноти відповідей респондентів

In [21]:
schema_questions = set(df1["qname"].dropna())
data_columns = set(df.columns)
valid_questions = schema_questions.intersection(data_columns)
valid_questions

{'AIAcc',
 'AIAgentChange',
 'AIAgentExtWrite',
 'AIAgentExternal',
 'AIAgentKnowWrite',
 'AIAgentKnowledge',
 'AIAgentObsWrite',
 'AIAgentObserveSecure',
 'AIAgentOrchWrite',
 'AIAgentOrchestration',
 'AIAgent_Uses',
 'AIAgents',
 'AIComplex',
 'AIExplain',
 'AIFrustration',
 'AIHuman',
 'AILearnHow',
 'AIModelsChoice',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'AIOpen',
 'AISelect',
 'AISent',
 'AIThreat',
 'Age',
 'AgentUsesGeneral',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'CompTotal',
 'Country',
 'Currency',
 'DatabaseChoice',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'DevEnvsChoice',
 'DevType',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'ICorPM',
 'Industry',
 'JobSat',
 'JobSatPoints_1',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_15_TEXT',
 'JobSatPoints_16',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'LanguageChoice',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'LearnCode',
 'LearnCodeAI',
 'LearnCodeChoose',
 'MainBranch',
 'NewRole',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'OrgSize',
 'PlatformChoice',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'PurchaseInfluence',
 'RemoteWork',
 'SOAccount',
 'SOComm',
 'SODuration',
 'SOFriction',
 'SOPartFreq',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'SOVisitFreq',
 'SO_Actions_1',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_7',
 'SO_Actions_9',
 'SO_Dev_Content',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechOppose_1',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'TechOppose_16',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'ToolCountPersonal',
 'ToolCountWork',
 'WebframeChoice',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'WorkExp',
 'YearsCode'}

In [18]:
filtered_df = df[list(valid_questions)]
filtered_df

,JobSatPoints_8,PlatformWantEntry,JobSatPoints_14,JobSatPoints_2,TechEndorse_8,CommPlatformWantEntr,AIAgentOrchestration,PurchaseInfluence,LearnCode,LearnCodeChoose,SO_Dev_Content,SO_Actions_4,SODuration,SO_Actions_16,SO_Actions_5,NewRole,AIThreat,JobSatPoints_16,TechEndorse_2,JobSatPoints_15,EmploymentAddl,SO_Actions_15,AIAgentObserveSecure,JobSatPoints_15_TEXT,Industry,JobSatPoints_5,DatabaseWantEntry,SO_Actions_6,AILearnHow,AIModelsHaveEntry,LanguagesHaveEntry,JobSatPoints_11,TechOppose_5,TechEndorse_1,LearnCodeAI,PlatformChoice,AIComplex,AIExplain,DevEnvsChoice,TechOppose_7,SO_Actions_15_TEXT,TechEndorse_7,AIAgent_Uses,AIFrustration,Age,PlatformHaveEntry,TechOppose_9,DevEnvHaveEntry,SO_Actions_10,AIAgents,SOPartFreq,AIAgentChange,DevEnvWantEntry,TechEndorseIntro,JobSatPoints_9,TechOppose_3,RemoteWork,WorkExp,JobSatPoints_1,ToolCountPersonal,OfficeStackWantEntry,TechOppose_16,LanguagesWantEntry,TechEndorse_4,AIAgentObsWrite,TechOppose_2,TechOppose_15,AIAgentKnowWrite,WebframeHaveEntry,TechOppose_15_TEXT,ToolCountWork,JobSatPoints_7,Employment,TechEndorse_6,TechOppose_11,TechEndorse_13_TEXT,AIOpen,JobSatPoints_13,Country,SO_Actions_7,JobSatPoints_6,LanguageChoice,AIModelsChoice,AIHuman,AISelect,DatabaseHaveEntry,AIAcc,SOFriction,AIModelsWantEntry,AIAgentOrchWrite,SOComm,JobSatPoints_3,SOTagsWant Entry,OfficeStackHaveEntry,MainBranch,SO_Actions_3,JobSatPoints_4,JobSat,AISent,SOTagsHaveEntry,TechEndorse_5,DevType,CompTotal,AIAgentExternal,CommPlatformHaveEntr,ICorPM,AgentUsesGeneral,EdLevel,SOAccount,TechOppose_1,YearsCode,TechEndorse_9,DatabaseChoice,TechEndorse_13,SO_Actions_1,JobSatPoints_10,TechOppose_13,WebframeChoice,WebframeWantEntry,SOVisitFreq,TechEndorse_3,SO_Actions_9,Currency,AIAgentExtWrite,AIAgentKnowledge,OrgSize
0,11.0,NaN,14.0,1.0,1.0,NaN,Vertex AI,"Yes, I influenced the purchase of a substantia...",Online Courses or Certification (includes all ...,"Yes, I am not new to coding but am learning ne...",NaN,2.0,Between 5 and 10 years,NaN,3.0,I have neither consider or transitioned into a...,I'm not sure,8.0,7.0,15.0,"Caring for dependents (children, elderly, etc.)",15.0,NaN,NaN,Fintech,5.0,NaN,7.0,AI CodeGen tools or AI-enabled apps,NaN,NaN,7.0,12.0,10.0,"Yes, I learned how to use AI-enabled tools for...",Yes,Bad at handling complex tasks,No,Yes,11.0,NaN,12.0,Software engineering,"AI solutions that are almost right, but not quite",25-34 years old,NaN,1.0,NaN,11.0,"Yes, I use AI agents at work monthly or infreq...",I have never participated in Q&A on Stack Over...,Not at all or minimally,NaN,Work,2.0,8.0,Remote,8.0,3.0,3.0,NaN,3.0,NaN,6.0,NaN,7.0,16.0,NaN,NaN,NaN,7.0,12.0,Employed,11.0,6.0,NaN,"Troubleshooting, profiling, debugging",13.0,Ukraine,9.0,10.0,Yes,Yes,When I don’t trust AI’s answers,"Yes, I use AI tools monthly or infrequently",NaN,Neither trust nor distrust,"Rarely, almost never",NaN,NaN,Neutral,4.0,NaN,NaN,I am a developer by profession,6.0,9.0,10.0,Indifferent,NaN,3.0,"Developer, mobile",52800.0,ChatGPT,NaN,People manager,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Yes,15.0,14.0,8.0,Yes,14.0,1.0,6.0,13.0,No,NaN,A few times per week,9.0,8.0,EUR European Euro,NaN,NaN,20 to 99 employees
1,2.0,NaN,14.0,8.0,5.0,NaN,NaN,No,Online Courses or Certification (includes all ...,"Yes, I am not new to coding but am learning ne...",Chat (people);Message Boards;Long-form article...,8.0,Between 10 and 15 years,NaN,2.0,I have transitioned into a new career and/or i...,I'm not sure,5.0,1.0,15.0,NaN,15.0,NaN,NaN,Retail and Consumer Services,12.0,NaN,4.0,AI CodeGen tools or AI-enabled apps,NaN,NaN,7.0,10.0,13.0,"Yes, I learned how to use AI-enabled tools for...",Yes,Bad at handling complex tasks,No,Yes,9.0,NaN,12.0,NaN,"AI solutions that are almost right, but not qu...",25-34 years old,NaN,3.0,NaN,11.0,"No, and I don't plan to","Infrequently, less than once per year",Not at all or minimally,NaN,Personal Project,11.0,13.0,"Hybrid (some in-person, leans heavy to flexibi...",2.0,10.0,5.0,NaN,5.0,NaN,9.0,NaN,1.0,15.0,NaN,NaN,NaN,6.0,6.0,Employed,3.0,4.0,NaN,All skills. AI is a flop.,13.0,Netherlands,10.0,1.0,Yes,Yes,When I don’t trust AI’s answers;When I want to...,"Yes, I use AI tools weekly",NaN,Neither trust nor distrust,About half of the time,NaN,NaN,"Yes, somewhat",3.0,NaN,NaN,I am a developer by profession,5.0,9.0,9.0,Indifferent,NaN,4.0,"Developer, back-end",90000.0,NaN,NaN,Individual contributor,NaN,"Associate degree (A.A., A.S., etc.)",Not sure/can't remember,14.0,10.0,7.0,Yes,14.0,6.0,4.0,2.0,Yes,NaN,Multiple times per day,2.0,9.0,EUR European Euro,NaN,NaN,500 to 999 employees
2,5.0,NaN,14.0,6.0,1.0,NaN,NaN,No,Online Courses or Certification (includes all ...,"Yes, I am not new to coding but am learning ne...",Chat (people);Videos;Lists of recommendations ...,5.0,Between 5 and 10 years,NaN,1.0,I have transitioned into a new career and/or i...,No,10.0,2.0,15.0,None of the above,15.0,NaN,NaN,Software Development,8.0,NaN,2.0,AI CodeGen tools or AI-enabled apps;Technical ...,NaN,NaN,3.0,12.0,12.0,"Yes, I learned how to use AI-enabled tools for...",Yes,Neither good or bad at handling complex tasks,No,Yes,13.0,NaN,13.0,Software engineering,"AI solutions that are almost right, but not qu...",35-44 years old,NaN,3.0,NaN,11.0,"Yes, I use AI agents at work weekly","Infrequently, less than once per year","Yes, somewhat",NaN,Work,2.0,2.0,NaN,10.0,9.0,3.0,NaN,11.0,NaN,7.0,NaN,1.0,15.0,NaN,NaN,NaN,3.0,1.0,"Independent contractor, freelancer, or self-em...",10.0,9.0,NaN,"Understand how things actually work, problem s...",13.0,Ukraine,9.0,12.0,Yes,Yes,When I don’t trust AI’s answers;When I want to...,"Yes, I use AI tools daily",NaN,Somewhat trust,About half of the time,NaN,NaN,Neutral,7.0,NaN,NaN,I am a developer by profession,4.0,11.0,8.0,Favorable,NaN,5.0,"Developer, front-end",2214000.0,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,NaN,Multi-platform search enablement,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Not sure/can't remember,8.0,12.0,4.0,Yes,14.0,3.0,4.0,4.0,Yes,Solid.js,A few times per week,3.0,7.0,UAH Ukrainian hryvnia,NaN,Redis,NaN
3,9.0,NaN,14.0,2.0,11.0,NaN,NaN,No,"Other online resources (e.g. standard search, ...","Yes, I am not new to coding but am learning ne...",Videos;Chat (bot/AI),5.0,Between 3 and 5 years,NaN,6.0,I have neither consider or transitioned into a...,No,3.0,12.0,15.0,None of the above,15.0,NaN,NaN,Retail and Consumer Services,6.0,NaN,7.0,AI CodeGen tools or AI-enabled apps;Videos (no...,NaN,NaN,12.0,4.0,2.0,"Yes, I learned how to use AI-enabled tools for...",Yes,Bad at handling complex tasks,NO,No,13.0,NaN,8.0,Software engineering,"AI solutions that are almost right, but not qu...",35-44 years old,NaN,12.0,NaN,11.0,"Yes, I use AI agents at work monthly or infreq...",I have never participated in Q&A on Stack Over...,Not at all or minimally,NaN,Personal Project,10.0,8.0,Remote,4.0,1.0,NaN,NaN,1.0,NaN,5.0,NaN,5.0,15.0,NaN,NaN,NaN,NaN,8.0,Employed,3.0,2.0,NaN,NaN,13.0,Ukraine,9.0,7.0,Yes,No,When I don’t trust AI’s answers;When I want to...,"Yes, I use AI tools weekly",NaN,Somewhat trust,"Rarely, almost never",NaN,NaN,Neutral,4.0,NaN,NaN,I am a developer by profession,4.0,5.0,6.0,Favorable,NaN,13.0,"Developer, back-end",31200.0,ChatGPT;Claude Code,NaN,Individual contributor,Language processing,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Yes,10.0,5.0,7.0,No,14.0,1.0,11.0,7.0,Yes,NaN,A few times per month or weekly,6.0,8.0,EUR European Euro,NaN,NaN,"10,000 or more employees"
4,5.0,NaN,10.0,4.0,4.0,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",NaN,"No, I am not new to coding and did not learn n...",Long-form articles,4.0,Between 5 and 10 years,NaN,2.0,I have neither consider or transitioned into a...,No,3.0,3.0,15.0,"Caring for dependents (children, elderly, etc.)",15.0,NaN,NaN,Software Development,14.0,NaN,5.0,Technical documentation (is generated for/by t...,NaN,NaN,1.0,9.0,6.0,"Yes, I learned how to use AI-enabled tools for...",Yes,"Good, but not great at handling complex tasks",partly,Yes,12.0,NaN,7.0,NaN,"AI solutions that are almost right, but not quite",35-44 years old,NaN,6.0,NaN,12.0,"No, and I don't plan to","Infrequently, less than once per year","Yes, to a great extent",NaN,Work,7.0,3.0,NaN,21.0,9.0,3.0,NaN,14.0,NaN,9.0,NaN,13.0,15.0,NaN,NaN,NaN,4.0,6.0,"Independent contractor, freelancer, or self-em...",8.0,1.0,NaN,"critical thinking, the skill to define the tas...",12.0,Ukraine,6.0,8.0,Yes,Yes,When I don’t trust AI’s answers,"Yes, I use AI tools weekly",NaN,Neither trust nor distrust,"Rarely, almost never",NaN,NaN,"No, not really",11.0,NaN,NaN,I am a developer by profession,7.0,13.0,7.0,Favorable,NaN,10.0,Engineering manager,60000.0,NaN,NaN,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",No,7.0,22.0,2.0,Yes,14.0,1.0,2.0,8.0,Yes,NaN,A few times per month or weekly,1.0,10.0,USD United States dollar,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I code primarily as a hobby,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Online Courses or Certification (includes all ...,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Caring for dependents (children, elderly, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45-54 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am a developer by profession,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some college/university study without earning ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,10.0,NaN,12.0,6.0,4.0,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Online Courses or Certification (includes all ...,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,I have somewhat considered changing my career ...,No,14.0,2.0,15.0,None of the above,NaN,NaN,NaN,Banking/Financial Services,4.0,NaN,NaN,AI CodeGen tools or AI-enabled apps;Videos (no...,NaN,NaN,8.0,7.0,9.0,"Yes, I learned how to use AI-enabled tools for...",NaN,"Good, but not great at handling complex tasks","Yes, partially.",NaN,5.0,NaN,8.0,NaN,"AI solutions that are almost right, but not qu...",35-44 years old,NaN,4.0,NaN,NaN,"No, I use AI exclusively in copilot/autocomple...",NaN,Not at all or minimally,NaN,Personal Project,2.0,2.0,"Hybrid (some in-person, leans heavy to flexibi...",17.0,3.0,35.0,NaN,8.0,NaN,5.0,NaN,6.0,10.0,NaN,NaN,NaN,25.0,1.0,Employed,7.0,1.0,NaN,NaN,11.0,Italy,NaN,9.0,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",NaN,Neither trust nor distrust,NaN,NaN,NaN,NaN,7.0,NaN,NaN,I am a developer by profession,NaN,13.0,9.0,Favorable,NaN,3.0,"Architect, software or solutions",80000.0,NaN,NaN,People manager,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,9.0,31.0,6.0,NaN,10.0,NaN,5.0,3.0,NaN,NaN,NaN,1.0,NaN,EUR European Euro,NaN,NaN,"10,000 or more employees"
49189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Videos (not associated with specific online co...,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am a developer by profession,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Online Courses or Certification (includes all ...,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Attending school (full-time),NaN,NaN,NaN,NaN,NaN,NaN,NaN,AI CodeGen tools or AI-enabled apps,NaN,NaN,NaN,NaN,NaN,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I am not primarily a developer, but I write co...",NaN,NaN,NaN,NaN,NaN,NaN,Student,NaN,NaN,NaN,NaN,NaN,Some college/university study without earning ...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
complete_responses = filtered_df.dropna()
complete_responses

Empty DataFrame
Columns: [JobSatPoints_8, PlatformWantEntry, JobSatPoints_14, JobSatPoints_2, TechEndorse_8, CommPlatformWantEntr, AIAgentOrchestration, PurchaseInfluence, LearnCode, LearnCodeChoose, SO_Dev_Content, SO_Actions_4, SODuration, SO_Actions_16, SO_Actions_5, NewRole, AIThreat, JobSatPoints_16, TechEndorse_2, JobSatPoints_15, EmploymentAddl, SO_Actions_15, AIAgentObserveSecure, JobSatPoints_15_TEXT, Industry, JobSatPoints_5, DatabaseWantEntry, SO_Actions_6, AILearnHow, AIModelsHaveEntry, LanguagesHaveEntry, JobSatPoints_11, TechOppose_5, TechEndorse_1, LearnCodeAI, PlatformChoice, AIComplex, AIExplain, DevEnvsChoice, TechOppose_7, SO_Actions_15_TEXT, TechEndorse_7, AIAgent_Uses, AIFrustration, Age, PlatformHaveEntry, TechOppose_9, DevEnvHaveEntry, SO_Actions_10, AIAgents, SOPartFreq, AIAgentChange, DevEnvWantEntry, TechEndorseIntro, JobSatPoints_9, TechOppose_3, RemoteWork, WorkExp, JobSatPoints_1, ToolCountPersonal, OfficeStackWantEntry, TechOppose_16, LanguagesWantEntry, TechEndorse_4, AIAgentObsWrite, TechOppose_2, TechOppose_15, AIAgentKnowWrite, WebframeHaveEntry, TechOppose_15_TEXT, ToolCountWork, JobSatPoints_7, Employment, TechEndorse_6, TechOppose_11, TechEndorse_13_TEXT, AIOpen, JobSatPoints_13, Country, SO_Actions_7, JobSatPoints_6, LanguageChoice, AIModelsChoice, AIHuman, AISelect, DatabaseHaveEntry, AIAcc, SOFriction, AIModelsWantEntry, AIAgentOrchWrite, SOComm, JobSatPoints_3, SOTagsWant Entry, OfficeStackHaveEntry, MainBranch, SO_Actions_3, JobSatPoints_4, JobSat, AISent, SOTagsHaveEntry, ...]
Index: []

In [20]:
complete_responses.shape[0]

0

Завдання 3. Статистичний аналіз досвіду респондентів

In [23]:
work_exp = df['WorkExp'].dropna()
print(f'Міри центральної тенденції :')
print(f'Mean: {round(work_exp.mean(), 1)}')
print(f'Median: {round(work_exp.median(), 1)}')
print(f'Mode: {round(work_exp.mode()[0], 1)}')

Міри центральної тенденції :
Mean: 13.4
Median: 10.0
Mode: 10.0

Завдання 4. Аналіз віддаленої роботи

In [24]:
remote_workers=(df['RemoteWork']=='Remote').sum()
print(remote_workers)

10931

Завдання 5. Визначення популярності Python

In [27]:
df['worked_with_python'] = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)
percent = df['worked_with_python'].sum()/len(df) * 100
print(f"Відсоток респондентів: {percent:.1f} %")

Відсоток респондентів: 37.5 %

Завдання 6. Аналіз шляхів навчання програмуванню

In [28]:
df['learn_method'] = df['LearnCode'].str.contains('online courses', case=False, na=False)
online_courses_count = df['learn_method'].sum()
print(online_courses_count)

10973

Завдання 7. Географічний аналіз компенсації Python-розробників

In [30]:
python_developers = df[(df['worked_with_python'])&(df['ConvertedCompYearly'].notna())]
py_progers_by_country = python_developers.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median']).reset_index()
py_progers_by_country

                                  Country           mean    median
0                             Afghanistan   22328.666667    1000.0
1                                 Albania   47217.600000   50000.0
2                                 Algeria   20187.285714    7088.0
3                                 Andorra  226103.500000  226103.5
4                     Antigua and Barbuda       1.000000       1.0
..                                    ...            ...       ...
148  Venezuela, Bolivarian Republic of...    9908.647059    3000.0
149                              Viet Nam  218837.166667    8254.0
150                                 Yemen   32929.500000   23672.0
151                                Zambia    5424.250000    3206.0
152                              Zimbabwe   34000.000000   25500.0

[153 rows x 3 columns]

Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [33]:
top_5 =df[['ResponseId', 'EdLevel', 'ConvertedCompYearly']].sort_values(by='ConvertedCompYearly', ascending=False).reset_index(drop=True)
top_5[['EdLevel']].head(5)

                                           EdLevel
0              Associate degree (A.A., A.S., etc.)
1  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
2              Associate degree (A.A., A.S., etc.)
3     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

*Завдання 9. Аналіз популярності Python по віковим категоріям

In [34]:
python_by_age = (df.groupby('Age')['worked_with_python'].mean() * 100).round(1).reset_index(name='Python_percent')
python_by_age

                 Age  Python_percent
0    18-24 years old            40.0
1    25-34 years old            36.9
2    35-44 years old            36.7
3    45-54 years old            38.6
4    55-64 years old            37.2
5  65 years or older            31.6
6  Prefer not to say            31.2

*Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [35]:
p75 = df['ConvertedCompYearly'].quantile(0.75)
high_paid_remote = df[(df['ConvertedCompYearly'] >= p75) & (df['RemoteWork'] == 'Remote')]
top_industries = (high_paid_remote['Industry'].value_counts().head(10))
top_industries

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Name: count, dtype: int64